src/models/OrganikiPrefrences.php
<?php

namespace Pasifai\Pysde\models;

use App\School;
use Illuminate\Database\Eloquent\Model;

class OrganikiPrefrences extends Model
{
    protected $table = 'organikes_prefrences';

    public  $timestamps = false;

    protected $fillable = [
        'request_id',
        'order_number',
        'school_id'
    ];


    protected $appends = [
        'OrganikiName',
        'OrganikiOrder',
        'OrganikiGroup'
    ];

    public function request()
    {
        return $this->belongsTo(OrganikiRequest::class,'request_id','id');
    }

    public function getOrganikiNameAttribute()
    {
        return School::find($this->school_id)->name;
    }

    public function getOrganikiOrderAttribute()
    {
        return School::find($this->school_id)->order;
    }

    public function getOrganikiGroupAttribute()
    {
        return School::find($this->school_id)->group_id;
    }
}

src/models/Protocol.php
<?php

namespace Pasifai\Pysde\models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Protocol extends Model
{
    protected $table = 'protocols';

    protected $fillable = [
        'id',
        'type',
        'p_date',
        'from_to',
        'subject',
        'f_id',
        'description',
        'printed',
        'pending'
    ];

    public function f()
    {
        return $this->belongsTo(F::class, 'f_id', 'id');
    }

    public function setPDateAttribute($date){
        $this->attributes['p_date'] = Carbon::createFromFormat('d/m/Y', $date);
    }

    public function getPDateAttribute($date)
    {
        return Carbon::parse($date)->format('d/m/Y');
    }

    public static  function LastProtocol()
    {
        $last_protocol = Protocol::orderBy('id', 'desc')->first();
        return ($last_protocol != null)? $last_protocol->id: 0;
    }

    public function getTypeAttribute($type){
        if ($type == 0){
            return 'Εισερχόμενο';
        }elseif($type == 1){
            return 'Εξερχόμενο';
        }elseif($type == 9){
            return 'Κενό';
        }
    }

    public function getFNameAttribute()
    {
        return $this->f->name;
    }

    public function getProtocolNameAttribute()
    {
        return $this->f_name . ' / ' . $this->id . ' / ' . str_replace('/','-',$this->p_date);
    }

    public function getIsNullAttribute()
    {
        if ($this->type == 9){
            return true;
        }else{
            return false;
        }
    }

    public function getYearAttribute()
    {
        return Carbon::createFromFormat('d/m/Y',$this->p_date)->format('Y');
    }

    public function getNowAttribute()
    {
        return Carbon::now()->format('Y');
    }
}

src/views/aitisis/PDF/aitisiPDF.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            font-size: 1em;
            text-align: justify;
        }

        table{
            width: 100%;
            margin-top: 3px;
            margin-bottom: 15px;
            border-collapse: collapse;
        }

        .withBorders td{
            border: 1px solid #000000;
        }

        .t1c1{
            font-size: 20pt;
            font-weight: bold;
            text-align: center;
        }
        .t1c2{
            text-align: center;
        }

        #t1c3s1{
            padding-left: 15px;
            font-size: 12pt;
        }

        #t1c3s2{
            font-size: 14pt;
            font-weight: bold;
        }

        .t1c4{
            text-align: center;
            font-size: 16pt;
            font-weight: 800;
        }

        #aitisi_type{
            font-size: 28pt;
            font-weight: bold;
            border: 1px solid #000000;
            text-align: center;
        }

        .greekHeader{
            font-size: 13pt;
            font-weight: 800;
            margin-left: 25px;
            border-bottom: 2px solid #000000;
            width: 200px;
        }

        .greekHeader3{
            font-size: 13pt;
            font-weight: 800;
            margin-left: 25px;
            border-bottom: 2px solid #000000;
            width: 380px;
        }

        .tableLabel{

        }

        .userTableData{
            font-weight: bold;
        }

        .table2Label{
            text-align: center;
        }
        .userTable2Data{
            font-weight: bold;
            text-align: center;
        }

        #moria{
            font-size: 15pt;
            font-weight: bold;
        }

        #organikiLabel{
            text-align: center;
            font-size: 10pt;
        }

        #organiki{
            font-size: 15pt;
            font-weight: bold;
            text-align: center;
        }

        .userDataNumbers{
            font-weight: bold;
        }

        .odigies{
            padding-left: 15px;
        }

        .table3Label{
            text-align: center;
        }
        .userTable3Data{
            padding-left: 15px;
        }
        #dilosi{
            text-align: center;
            font-weight: bold;
            font-size: 13pt;
        }
        .date_signature{
            text-align: center;
        }
        #date_value{
            font-weight: bold;
            font-size: 14pt;
        }

        #descriptions{

        }
    </style>

</head>
<body class="page" marginwidth="0" marginheight="0">
    @if($request_teacher->aitisi_type == 'E1')
        @include('pysde::aitisis.type.E1')
    @elseif($request_teacher->aitisi_type == 'E2')
        @include('pysde::aitisis.type.E2')
    @elseif($request_teacher->aitisi_type == 'E3')
        @include('pysde::aitisis.type.E3')
    @elseif($request_teacher->aitisi_type == 'E4')
        @include('pysde::aitisis.type.E4')
    @elseif($request_teacher->aitisi_type == 'E5')
        @include('pysde::aitisis.type.E5')
    @elseif($request_teacher->aitisi_type == 'E6')
        @include('pysde::aitisis.type.E6')
    @elseif($request_teacher->aitisi_type == 'E7')
        @include('pysde::aitisis.type.E7')
    @endif
</body>
</html>

src/views/aitisis/PDF/simpleAitisiPDF.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            font-size: 1em;
            text-align: justify;
        }

        table{
            width: 100%;
            margin-left: 20px;
            margin-right: 20px;
            margin-top: 3px;
            margin-bottom: 15px;
            border-collapse: collapse;
        }

        .withBorders td{
            border: 1px solid #000000;
        }

        .t1c1{
            font-size: 22pt;
            font-weight: bold;
            text-align: center;
            letter-spacing: 5px;
        }


        #t1c3s1{
            padding-left: 15px;
            font-size: 16pt;
        }

        #t1c3s2{
            font-size: 18pt;
            font-weight: bold;
        }

        .t1c4{
            /*text-align: center;*/
            font-size: 16pt;
            font-weight: 800;
            padding-left: 30px;
        }

        #description{
            padding-left: 20px;
            line-height: 200%;
            text-align: justify;
            font-size: 14pt;
        }

        .line-data{
            font-size: 14pt;
            margin-bottom: 40px;
        }

        .data{
            font-size: 15pt;
            font-weight: bold;
        }

    </style>

</head>
<body class="page" marginwidth="0" marginheight="0">

    <table>
        <tbody>
            <tr>
                <td width="50%"></td>
                <td width="50%">
                    <div><span id="t1c3s1">Αρ. Πρωτ. :</span></div>
                    <div><span id="t1c3s2">{!! $protocol->protocol_name !!}</span> </div>
                </td>
            </tr>
            <tr>
                <td width="50%">
                    <div class="t1c1">ΑΙΤΗΣΗ</div>
                </td>
                <td width="50%">
                </td>
            </tr>
            <tr>
                <td width="50%" valign="top">
                    <br>
                    <br><br><br>
                    <div class="line-data">
                        <span class="label">ΕΠΩΝΥΜΟ:</span>
                        <span class="data">{!! $request_teacher->teacher->user->last_name !!}</span>
                    </div>
                    <div class="line-data">
                        <span class="label">ΟΝΟΜΑ:</span>
                        <span class="data">{!! $request_teacher->teacher->user->first_name !!}</span>
                    </div>
                    <div class="line-data">
                        <span class="label">ΟΝ. ΠΑΤΡΟΣ:</span>
                        <span class="data">{!! $request_teacher->teacher->middle_name !!}</span>
                    </div>
                    <div class="line-data">
                        <span class="label">ΔΙΕΥΘΥΝΣΗ:</span>
                        <span class="data">{!! $request_teacher->teacher->address !!}</span>
                    </div>
                    <div class="line-data">
                        <span class="label">ΤΗΛΕΦΩΝΟ:</span>
                        <span class="data">{!! $request_teacher->teacher->phone !!}</span>
                    </div>
                    <br><br><br>
                    <div class="line-data">
                        <span class="label">ΚΛΑΔΟΣ:</span>
                        <span class="data">{!! $request_teacher->teacher->klados_name !!} ({!! $request_teacher->teacher->eidikotita_name !!})</span>
                    </div>
                    @if($request_teacher->teacher->teacherable_type == 'App\Monimos')
                        <div class="line-data">
                            <span class="label">ΣΧΕΣΗ ΕΡΓΑΣΙΑΣ:</span>
                            <span class="data">ΜΟΝΙΜΟΣ</span>
                        </div>
                        <div class="line-data">
                            <span class="label">ΑΡΙΘΜΟΣ ΜΗΤΡΩΟΥ:</span>
                            <span class="data">{!! $request_teacher->teacher->teacherable->am !!}</span>
                        </div>
                        <div class="line-data">
                            <div><span class="label">ΟΡΓΑΝΙΚΗ ΘΕΣΗ:</span></div>
                            <div><span class="data">{!! $request_teacher->teacher->teacherable->organiki_name !!}</span></div>
                        </div>
                    @elseif($request_teacher->teacher->teacherable_type == 'App\Anaplirotis')
                        <div class="line-data">
                            <span class="label">ΣΧΕΣΗ ΕΡΓΑΣΙΑΣ:</span>
                            <span class="data">ΑΝΑΠΛΗΡΩΤΗΣ</span>
                        </div>
                        <div class="line-data">
                            <span class="label">ΑΦΜ:</span>
                            <span class="data">{!! $request_teacher->teacher->teacherable->afm !!}</span>
                        </div>
                    @endif
                    <div class="line-data">
                        <div><span class="label">ΣΧΟΛΕΙΟ ΠΟΥ ΥΠΗΡΕΤΕΙ:</span></div>
                        <div><span class="data">{!! $request_teacher->schools_that_is !!}</span></div>
                    </div>
                    <br><br><br>
                    <div class="line-data">
                        <div><span class="label">ΘΕΜΑ:</span></div>
                        <div><span class="data">{!! $request_teacher->subject !!}</span></div>
                    </div>
                    <br><br><br>
                </td>

                <td valign="top" width="50%">
                    <br><br>
                    <div class="t1c4">Προς το</div>
                    <div class="t1c4">Π.Υ.Σ.Δ.Ε. Χανίων</div>
                    <br><br>
                    <div id="description">
                        Παρακαλώ {!! $request_teacher->description !!}
                    </div>
                </td>
            </tr>

            <tr>
                <td width="50%">
                    <div class="line-data">
                        <span class="label">ΧΑΝΙΑ</span>
                        <span class="data">{!! $request_teacher->date_request !!}</span>
                    </div>
                </td>
                <td width="50%" align="center">
                    Ο ΑΙΤΩΝ
                </td>
            </tr>
        </tbody>
    </table>

</body>
</html>